### ISSUE TITLE
Computation time and memory requirements

### ISSUE THREAD

**Issue by opain** [getian107/PRScsx#15]
Dear Tian Ge,

Thank you and your team for developing this exciting method!

Please can you indicate the required memory and computation time to run PRS-CSx, for example without parallel computing for one phi parameter on chromosome 1 (HapMap3 only), with default settings but --meta=True? Or please point me towards previous documentation regarding this aspect of PRS-CSx.

I imagine PRS-CSx with two sets of sumstats and --meta=True will be use slightly more memory and run for three times as long as PRScs with one set of sumstats?

Many thanks,

Ollie

**Comment by getian107** [comment]
Hi Ollie- PRS-CSx with two sets of sumstats will roughly double the runtime and memory requirements of PRS-CS if the same number of MCMC iterations is used. We now recommend running a longer chain for PRS-CSx to improve convergence. For two sets of sumstats, if the length of the MCMC chain is doubled (default setting), the computation time is ~4x. --meta=True adds negligible computational cost.

**Comment by opain** [comment]
Great! Thank you Tian for your clear and prompt response.
