### ISSUE TITLE
setting mcmc iterations reverts to default

### ISSUE THREAD

**Issue by rmandla** [getian107/PRScsx#16]
Hi Tian,

I want to run prs-csx with many MCMC iterations, but when I set the number with --n_iter, only the default 1,000 iterations * number of populations are run. Looking at the source code, it seems I am running into this issue because I am not changing the --n_burnin value, so --n_iter is set back to default. Is this intentional? And if so, would you be able to update the docs to indicate it and/or have prs-csx raise an error if one is set without the other?

Thanks!

**Comment by getian107** [comment]
Hi- yes this is intentional because usually a longer MCMC chain is coupled with a larger number of burnin steps, and it doesn't make sense to set n_burnin > n_iter. I'll update the docs. Meanwhile if you set both values you should be able to run a chain with desired iterations.

**Comment by rmandla** [comment]
Thanks!
