### ISSUE TITLE
A follow-up tutorial on calculating polygenic score

### ISSUE THREAD

**Issue by fys666** [getian107/PRScsx#19]
Dear Tian,

First,Thank you for your valuable tool for PRS analysis. It really helps me a lot.

I'm new to the genetics. May I ask the key follow-up parts, such as how the results built using your example files can be combined with plink? That is to say, how to use the results of PRScsx and plink to calculate the polygenic score?

Could you give a more detailed tutorial? I looked at plink's tutorial and found that they provide three extra files in addition to the results given by PRScsx.

Binary file containing sample identifier (ID) and genotype (*.bed);
Contains relevant individual information files (*.fam);
Genetic marker files (*.bim).

For example:
plink \
    --bfile EUR.QC \
    --score result_EAS_pst_eff_a1_b0.5_phi1e-02_chr22.txt 2 4 6 \
    --out EUR

They provide "--bfile". These are the three documents I mentioned earlier. Could you please provide them as well?

Sorry for my poor English.

Bests,

fys

**Comment by getian107** [comment]
Hi- The three files (.bed, .bim and .fam) correspond to your target dataset (i.e., the dataset in which you would like to evaluate the performance of the polygenic score). Briefly PRS-CS(x) provides adjusted SNP weights using GWAS summary statistics. You can then take those weights to your target dataset to calculate individual-level polygenic scores. Let me know if you need more information. And if you are new to genetics and PRS analysis, this review might be helpful: https://www.nature.com/articles/s41596-020-0353-1

**Comment by fys666** [comment]
Thanks for your quick reply and the review you recommend.
Have a good day!
