### ISSUE TITLE
2 summary statistics with the same population

### ISSUE THREAD

**Issue by milo2992** [getian107/PRScsx#20]
Dear Dr. Tian,

I have a question. Can I use 2 summary statistics with the same population? When I run it I only got one output ? 
I wonder how the software handles it ?

Thank you,

**Comment by getian107** [comment]
Hi- We generally recommend meta-analyzing summary statistics from the same population and then use PRS-CS or PRS-CSx. As we discussed in the article: "PRS-CSx is designed to flexibly model GWAS summary statistics from multiple populations where SNP effect sizes and/or LD patterns differ. For two or more GWAS conducted in independent samples from the same population where effect sizes and LD patterns are expected to be highly concordant, a fixed-effect meta-analysis is probably the optimal approach to combine the GWAS and maximize statistical power."

I think the current coding of the program probably only allows for one output from each population, and requires some modifications to handle multiple summary statistics from the same population. Let me know if there is a strong reason that you think summary stats from the same population should be modeled separately.

**Comment by milo2992** [comment]
Dear Dr. Tian,

Thank you so much for your response. 

We have multi-ethnic GWAS(AFR,EUR,EAS,HIS)and 60 % of the sample are EUR ancestry; we want to set them as EUR ancestry, and the second GWAS is 100 % EUR. We want to model them separately as EUR ancestry. In addition, we would like to compare when we set Multi-ethnic GWAS as AFR. Perhaps we can use PRS-CSx to perform this analysis.

Thank you.

**Comment by getian107** [comment]
In this case I think you could meta-analyze the multi-ethnic GWAS with the EUR GWAS and use PRS-CS for PRS calculation (i.e., assuming both GWAS are EUR), and compare the prediction with PRS-CSx where you can use the AFR reference panel for the multi-ethnic GWAS.

**Comment by harryyiheyang** [comment]
Could I rename the LD reference files to manually (e.g., rename an reference folder to be AFR) and then perform the joint estimation of PRSCSX described above? A directly reason for this purpose is jointly estimating the PRSCSX of two highly-correlated traits, one with larger samplesize while the other with lower sample size.

**Comment by getian107** [comment]
I think you likely need to make some small modifications to the code to allow for the input of two GWAS from the same populations. Alternatively, you could apply PRS-CS to each GWAS separately and combine the resulting PRS - similar to what many of the multi-PRS methods are doing. PRS-CSx hasn't been evaluated in the multi-trait context and it's possible that it produces prediction accuracy similar to that of multi-PRS.
