### ISSUE TITLE
B38 References

### ISSUE THREAD

**Issue by BEFH** [getian107/PRScsx#21]
Could you please let me know how to build PRS-CSx/PRS-CS references so that I can use the gnomAD joint 1KG/HGDP reference in both b37 and b38 or make b38 references available?

**Comment by getian107** [comment]
Hi- Thanks for reaching out! Here is some guidance for building reference panels for PRS-CS: https://github.com/getian107/PRScs/issues/20
PRS-CS is robust to different panels; a larger reference may not significantly improve prediction.
Also note that PRS-CS matches SNPs between the reference, summary stats and target dataset using rs ID and the two alleles. The base pair in the output is for information only and is not used in any computation.
Let me know if you have further questions.
