### ISSUE TITLE
Loading python libraries

### ISSUE THREAD

**Issue by BasilioCieza** [getian107/PRScsx#22]
Hello getian107,

Thank you for your nice work, I am Basilio, I hope you are doing well. I am having an issue that I think, and I wanted to report (If I am wrong, please, feel free to correct me).

I follow the steps corresponding to 'getting started'... however, when I run the main code (python PRScsx.py), I got the next error message:

Traceback (most recent call last):
  File "/mnt/mfs/hgrcgrid/shared/GT_ADMIX/Basilio_08_19_2022/pg_score/PRScsx2/PRScsx-master/PRScsx.py", line 90, in <module>
    import mcmc_gtb
  File "/mnt/mfs/hgrcgrid/shared/GT_ADMIX/Basilio_08_19_2022/pg_score/PRScsx2/PRScsx-master/mcmc_gtb.py", line 11, in <module>
    from scipy import random
ImportError: cannot import name 'random' from 'scipy' (/home/bc3045/conda/my-envs/PRScsx/lib/python3.11/site-packages/scipy/__init__.py)

What I did is simply replace "from scipy import random" by  "from scipy.sparse import random"

and it worked, however, I wanted to double check with you cause it seems a very obvious issue and it is weird nobody reported it.

Thank you for your time and patience,

Basilio

**Comment by getian107** [comment]
Hi Basilio,

This has been reported recently in PRS-CS:
https://github.com/getian107/PRScs/issues/49

I think replacing scipy with numpy will fix the issue. I will update the code when I get a chance.

**Comment by BasilioCieza** [comment]
Ah ok, I just wanted to double check. Thank you for your soon answer!!
