### ISSUE TITLE
Error reading my summary statistics

### ISSUE THREAD

**Issue by BasilioCieza** [getian107/PRScsx#23]
Dear getian107,

Hope you are doing well. I am writing to you because I am having an issue running the PRScsx. I ran the test data succefully, however, when I use my own summary statistics (same chromosome, same format, etc). I get the next error message (below). I have two population, lets say P1 and P2, when I put P1 first I got this message: KeyError: 'FRQ_P1'. When I put P2 first, I got KeyError: 'FRQ_P2'. I think this suggest it is not being hable to read any one of my inputs files.

... 986 SNPs read from /home/bc3045/PRScsx_testdata/PRScsx-master/test_data/hable_chr22_prs_ready_filtered.txt ...
Traceback (most recent call last):
  File "/mnt/mfs/hgrcgrid/homes/bc3045/PRScsx_testdata/PRScsx-master/PRScsx.py", line 215, in <module>
    main()
  File "/mnt/mfs/hgrcgrid/homes/bc3045/PRScsx_testdata/PRScsx-master/PRScsx.py", line 198, in main
    sst_dict[pp] = parse_genet.parse_sumstats(ref_dict, vld_dict, param_dict['sst_file'][pp], param_dict['pop'][pp], param_dict['n_gwas'][pp])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/mfs/hgrcgrid/homes/bc3045/PRScsx_testdata/PRScsx-master/parse_genet.py", line 81, in parse_sumstats
    idx = [ii for (ii,frq) in enumerate(ref_dict['FRQ_'+pop.upper()]) if frq>0]
                                        ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'FRQ_HABLE'

This is how my input sum statistic look like:

POPULATION1 
SNP     A1      A2      BETA    P
rs9605903       T       C       -0.101997       0.214901
rs5747999       C       A       0.0117889       0.841379

POPULATION 2

SNP     A1      A2      BETA    P
rs9605903       T       C       -0.0175513      0.944818
rs5747999       C       A       0.0477803       0.829321

**Comment by getian107** [comment]
Hi- Could you send the commend line you used to call PRS-CSx? Note that the input of --pop can only be one of the followings: AFR, AMR, EAS, EUR and SAS. This might explain the issue you had?
