### ISSUE TITLE
Performance improvements?

### ISSUE THREAD

**Issue by mglev1n** [getian107/PRScsx#26]
Although PRScsx allows for parallel computations of PRS across chromosomes, the time to generate score across all chromosomes is still substantial (eg. several hours of parallel computation). This is quite reasonable when dealing with a small number of traits, but for larger-scale analyses this becomes computationally prohibitive. Reducing the number of MCMC iterations seems like one way to improve performance, but I'm not sure about the "safety" of this approach. Are there other performance optimizations being considered for the future?

**Comment by getian107** [comment]
Hi - Reducing the number of MCMC iterations will likely slightly reduce prediction accuracy. You might want to benchmark on a small number of traits. We are working on faster MCMC samplers and model fitting algorithms. This will take some time but hopefully will improve computational efficiency in the near future.
