### ISSUE TITLE
LD reference panel for SAS

### ISSUE THREAD

**Issue by QinqinHuang** [getian107/PRScsx#3]
Hi Tian,

Thank you for making this tool available and we would like to try this method to improve portability of PRSs into South Asians.

I realise that LD reference data are provided for Europeans, East Asians, and Africans, but not for South Asians. I am just wondering if you guys plan to build one? If not, I think I can follow the instructions you shared previously (https://github.com/getian107/PRScs/issues/20) and build a reference panel using South Asian individuals (N=489) from the 1000 Genomes project. 

Many thanks,
Qinqin

**Comment by dheeraj-bobbili1988** [comment]
Hi Tian,

+1 for this request. I am also looking for the PRSs for South Asians. 

Thank you @QinqinHuang  for raising this topic.

Look forward to your response,

Regards,
Dheeraj

**Comment by getian107** [comment]
Hi Qinqin and Dheeraj,

Thanks for the feedback. I've now added reference panels (AFR, EAS, EUR and SAS) constructed from UK Biobank samples. Hope these help. Let me know if you have further questions/suggestions.

All the best,

-Tian
