### ISSUE TITLE
coordinate input

### ISSUE THREAD

**Issue by SheaCheng2000** [getian107/PRScsx#30]
Hi,

Can I use the coordinate like chr1:224568215:A:C as the input of `SUM_STATS_FILE` 's SNP row rather than the rsID?  
Maybe when I make it consistent with the second row of bim file, it will work?

Thanks!

Shea

**Comment by getian107** [comment]
Hi Shea- Currently only rsID works as the SNP identifier because the reference panel was built using rsID. Sorry for any inconvenience.

**Comment by SheaCheng2000** [comment]
Hi Tian, 

Thanks for your quick response! It's okay and I will use VEP to annotate the rsID.)

Shea
