### ISSUE TITLE
Please specify the directory bim file

### ISSUE THREAD

**Issue by adrianalori17** [getian107/PRScsx#31]
Hello, most probably this is a really easy fix. 
I cloned PRScsx and I am using Python in Windows. 
I tried all different combinations for the bim file but I always get back with the same error: 

C:\~\Python311\python S:\USER\ALORI\4paperAL\PRScsx\PRScsx.py –-ref C:\Users\adrianalori\Desktop\SummaryStatistics_desktop\aa\ldblk_1kg_afr --bim_prefix C:\Users\adrianalori\Desktop\SummaryStatistics_desktop\test_data\test.bim ...

* Please specify the directory and prefix of the bim file for the target (validation/testing) dataset using --bim_prefix

I would like also have some suggestions. My target population is African American and my GWAS summary statistic is European/ 
I downloaded European, African and Amr. Should I use all three as reference? 

Thank you so much for any help you can give me
Best
Adriana

**Comment by adrianalori17** [comment]
I changed to a MAC and the codes now work.
Do you have a suggestion about the best way to analyze an African American with a Europena  GWAS summary statistic ? For now I 
 am using AMR as reference.

**Comment by getian107** [comment]
Hi Adriana- The reference panel should match the ancestry of the GWAS sample. If you have a GWAS conducted in individuals of European ancestry, you should use EUR as the reference panel regardless of the ancestry of your target sample.
