### ISSUE TITLE
PRScsx  

### ISSUE THREAD

**Issue by Reta-Dewau** [getian107/PRScsx#34]
Dear Dr Tian,

I have tried to excercise the tutorial of PRScsx.
I have experienced *Please specify the output directory using --out_dir problen repeatedly even I had specified it 

python3.10 PRScsx.py --ref_dir=/data/alh-admyim/study3/ldblk_ukbb_amr --bim_prefix=test_data/test --sst_file=test_data/EUR_sumstats.txt,test_data/EAS_sumstats.txt --n_gwas=200000,100000 --pop=EUR, EAS --chrom=22 --phi=1e-2 --out_dir=/data/alh-admyim/study3/PRS_out --out_name=mytest

I really appreciate for the development of cross ancestry PRS estimation software and it is very helpful for researchers and students like me.

**Comment by getian107** [comment]
Hi Reta - I think replied to your question via email but let me know if you have further questions.
