### ISSUE TITLE
error "not reading the --n_gwas parameter"

### ISSUE THREAD

**Issue by sevi2018** [getian107/PRScsx#36]
Hello, 
I am trying to run PRScsx but keep getting the same error, 
I have tried everything space, and different order of parameters in the command but keep getting the same error.

./PRScsx.py --ref_dir=./reference/ --bim_prefix=./test_data/all_chrs.Q6.bim --sst_file=./test_data/EUR_OD_exposed_cases_controls.txt, ./test_data/AFR_OD_exposed_cases_controls.txt --n_gwas=5500,2300 --pop=EUR,AFR --out_dir=./output_files/ --out_name=chr22 --chrom=22 --phi=1E-02

* Please provide the sample size of the GWAS using --n_gwas

Do you see anything wrong in this command? 

Thank you in advance

**Comment by getian107** [comment]
Hi - Could you try removing the space after the comma when specifying the summary stats using --sst_file and see if this resolves the issue?

**Comment by sevi2018** [comment]
Thank you for your response,
it works now
