### ISSUE TITLE
Reference Genomes and LD

### ISSUE THREAD

**Issue by brunomiwa** [getian107/PRScsx#38]
Sorry if it's a dumb question. 

From what I could gather, the reference LD panels provided by PRS-CSx authors are on GRCh37. If I had data on GRCh38, the best practice would be to lift over from 38 to 37?

**Comment by getian107** [comment]
Hi - Yes it would be good to do the lift over. But PRS-CS/x uses rsID, A1 and A2 to match SNPs. The base pair position is for reference only and is not used in any calculation or variant matching. So even if you don't do the lift over the impact should be minimal in vast majority of the cases.
