### ISSUE TITLE
combine the PRS estimates from different ancestries

### ISSUE THREAD

**Issue by sevi2018** [getian107/PRScsx#39]
Hello there,

I have used PRScsx to estimate PRS based on GWAs summary statistics for individuals of African and European ancestry. Now, I am going to use the PRS to predict a quantitative trait in a small cohort of ~ 150 individuals, out of which 90% are Caucasians and the rest are African American.

Since I do not have enough samples to predict the trait separately for each ancestry, I am wondering if you could suggest the best approach to combine the PRS estimates from both ancestries.

Thank you

**Comment by getian107** [comment]
Hi - This is a challenging question as the inclusion of both European and African American samples in the evaluation model poses the risk of population stratification. There doesn't seem to be a perfect solution to me and I'd suggest looking for additional independent testing samples if possible.
