### ISSUE TITLE
The UKB Reference is GRCh37?

### ISSUE THREAD

**Issue by koujiaodahan** [getian107/PRScsx#43]
The UKB Reference is GRCh37?

**Comment by koujiaodahan** [comment]
And I noticed that the  1000genome LD panel  in the directory is also GRCh37?

**Comment by getian107** [comment]
Yes they are in GRCh37. But note that PRS-CS/x uses rs ID, A1 and A2 to match SNPs; the base pair position is for reference only and is not used in any calculation. As a result genome build usually has a minimal impact on the result.

**Comment by koujiaodahan** [comment]
> Yes they are in GRCh37. But note that PRS-CS/x uses rs ID, A1 and A2 to match SNPs; the base pair position is for reference only and is not used in any calculation. As a result genome build usually has a minimal impact on the result.

Thanks for your reply,  and  I will not liftover the positon, and guarantee the rsID, A1, A2.

**Comment by koujiaodahan** [comment]
> Yes they are in GRCh37. But note that PRS-CS/x uses rs ID, A1 and A2 to match SNPs; the base pair position is for reference only and is not used in any calculation. As a result genome build usually has a minimal impact on the result.

Hi, would you recommend the dbsnp version for annotating rsID? I noticed that a specific position is named by different rsID in different dbsnp version
<img width="898" alt="image" src="https://github.com/getian107/PRScsx/assets/26478793/810c298d-7ca0-48cf-a909-b4f9a612e3e4">
