### ISSUE TITLE
Question: hg19 and hg38 format

### ISSUE THREAD

**Issue by jasmine9764** [getian107/PRScsx#5]
Dear Ge Tian,
We are trying to test your excellent tool in east asian population, however, as our biobank imputation data is released in hg38 version while the PRS-CSx LD reference panels was constructed as hg19 from 1000 Genomes. To be specific, we might need .bed instead of .hdf5. We know there is tool online (eg ucsc annotation) but it might be time-consuming and we are not sure if the coverage rate will affect our resul.

I look forward to your opinion. Thank you so much!

Jasmine

**Comment by getian107** [comment]
Hi Jasmine, PRS-CS and PRS-CSx use rs ID, A1 and A2 to match SNPs between summary statistics, reference panels and the target dataset. Base pair positions are not used in any computation and are included for reference only. I don't think there will be any meaningful differences in results using hg19 vs. hg38.
