### ISSUE TITLE
SUM_STATS file cannot be CSVs based on parse_sumstats function

### ISSUE THREAD

**Issue by chen70335** [getian107/PRScsx#52]
Hi, in your description here: "SUM_STATS_FILE (required): Full path and the file name of the GWAS summary statistics. Multiple GWAS summary statistics files are allowed and should be separated by comma." you mentioned that it should be separated by comma, but the parse_sumstats function in parse_genet.py only splits by white space/ tab on line 73.

**Comment by getian107** [comment]
The description refers to the command line that specifies the directory and name of the summary statistics files. For instance:

--sst_file=Sumstats1.txt,Sumstats2.txt

Note that the two file names are separated by comma.

parse_genet.py parses the content of the summary statistics files, in which the columns (SNP, A1, A2, etc) should be separated by space or tab.
