### ISSUE TITLE
Parallel computation with PRScsx-auto causes diverse shrinkage parameters

### ISSUE THREAD

**Issue by Xi-Cao** [getian107/PRScsx#53]
Hi again, and thanks for your helpful response last time! I have a new question regarding PRScsx-auto.

When performing parallel computation for all 22 autosomes as recommended, PRScsx-auto estimates a global shrinkage parameter for each chromosome separately, rather than applying a single parameter to all chromosomes, just like when we specify the parameter as 1e-6. Is this acceptable?

Thanks，
xicao

**Comment by getian107** [comment]
Yes - this is desired and provides the model with more flexibility to adapt to potentially different genetic architectures across chromosomes.

**Comment by Xi-Cao** [comment]
I see, thank you!
