### ISSUE TITLE
How to get P value?

### ISSUE THREAD

**Issue by YangRT11** [getian107/PRScsx#58]
Hi, I found that we can only get a posteriori beta values for our output file, can you please tell me how to get other effect values such as se and P, which is very useful for filtering of thresholds when constructing PRS.

**Comment by YangRT11** [comment]
Thank you!
May I ask if I want to construct a PRS using only some of the SNPs in the GWAS summary data (e.g. only SNPs with P<5E-8 are needed). Which of the following should I follow:
1. Input file incorporating only SNPs with P<5E-8 and run PRS-CSx
OR:
2. Input file incorporates all SNPs from the GWAS summary data, and after running PRS-CSx, select the SNPs with P<5E-8 from the original GWAS from the output file, and further plink to build the PRS

**Comment by getian107** [comment]
Bayesian PRS methods are developed to use genome-wide common variants. If you want to build a score using only genome-wide significant loci, you should check out the "clumping and thresholding" method and software. For example:  https://choishingwan.github.io/PRSice/
