### ISSUE TITLE
Which output file should be selected to build the PRS if there are no validation samples?

### ISSUE THREAD

**Issue by YangRT11** [getian107/PRScsx#59]
Due to the small sample size of my target population, I was unable to isolate the validation population. I found the 'auto' and 'meta' version of the PRS-CSx algorithm can be used to construct a PRS, which does not require a validation dataset to tune hyper-parameters. 

My question is, if I have two GWAS summary data for the EUR (larger sample size, more significant snps) and EAS (very small sample size, fewer significant snps) populations, they are my base sample. And my target sample is an EAS population. So:

1. which posterior beta of EUR, EAS, META from PRS-CSx output should I use to construct PRS for my target population?
(EUR-GWAS has a lot of significant findings, I initially used only EUR-GWAS to construct the PRS, but it seems inappropriate to apply it directly to the EAS population, that's why I introduced the small sample EAS-GWAS.)

2. If I select only the EUR posterior beta out of the three output files of PRS-CSx (EUR, EAS, META) to construct the PRS. Does this already take into account the characteristics of the EAS population? Or does it make the same sense as constructing PRS with only EUR-GWAS.
(I found that building PRS with EUR posterior-beta output from PRS-CSx works better with my target population than building PRS with META)

I think I still don't have a good understanding of exactly what each output file of the PRS-CSx means, looking forward to your explanation, thanks!

**Comment by getian107** [comment]
If you would like to use the 'meta' + 'auto' approach, you'd use the META file from the output, which combines SNP weights from the two input GWAS.

**Comment by YangRT11** [comment]
Thank you! Can I understand that if I only use EUR posterior beta to build PRS, it is equivalent to using the PRS-CS method, and does not take into account the effect of the EAS population.

**Comment by getian107** [comment]
The EUR posterior beta is influenced by EAS GWAS (through the coupled prior) and is thus slightly different from running PRS-CS on EUR GWAS only, but it's still considered as a set of EUR-specific effects (in contrast to the META effects which fully integrate EUR and EAS GWAS).
