### ISSUE TITLE
Output meta=True

### ISSUE THREAD

**Issue by patinolr** [getian107/PRScsx#61]
Hi Tian,

Thank you for this amazing tool! I saw that you recently updated to have meta=True to allow the output of all posterior samples. In this file could you explain the number of columns represents.

**Comment by getian107** [comment]
Hi - When both '--meta' and '--write_pst' are set to True, the software will output all posterior samples of the SNP effect sizes. Each column represents one posterior sample, and the number of columns represents the total number of posterior samples after excluding burnin samples and accounting for thinning.

**Comment by patinolr** [comment]
Perfect, thank you so much for your prompt response! So, if I understand correctly, from those values one can obtain the posterior means and variance to estimate the individuals PRS and confidence interval?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by getian107** [comment]
Yes - exactly. For more background, you can check out this paper: https://www.nature.com/articles/s41588-021-00961-5
