### ISSUE TITLE
Time consuming and low computing resource used

### ISSUE THREAD

**Issue by caozilongsuper** [getian107/PRScsx#62]
Hi, professor Ge.
I would like to express my sincere gratitude for the incredible analysis method you have developed. The functionality it offers is truly powerful, and I have greatly appreciated its potential in my work.

However, I have encountered an issue regarding the program's performance. Specifically, the execution time is relatively long, and I have noticed that it doesn't seem to utilize idle computing resources, especially during the --iter process. This is impacting the overall efficiency of the process.

Here is an example log of the script
--ref_dir=genotypes/PRS-CS/1KG
--bim_prefix=result/PRSCSx/data/geno2/combinded
--sst_file=['result/PRSCSx/temple/Pancreatic_EUR.txt', 'result/PRSCSx/temple/Pancreatic_EAS.txt']
--a=1
--b=0.5
--phi=None
--n_gwas=[350043, 113491]
--pop=['EUR', 'EAS']
--n_iter=2000
--n_burnin=1000
--thin=5
--out_dir=result/PRSCSx/result2/Pancreatic
--out_name=Pancreatic_pst_eff_a1_b0.5_phiauto_chr1
--chrom=['1']
--meta=TRUE
--seed=None

*** 2 discovery populations detected ***

##### process chromosome 1 #####
... parse reference file: genotypes/PRS-CS/1KG/snpinfo_mult_1kg_hm3 ...
... 109168 SNPs on chromosome 1 read from genotypes/PRS-CS/1KG/snpinfo_mult_1kg_hm3 ...
... parse bim file: result/PRSCSx/data/geno2/combinded.bim ...
... 108029 SNPs on chromosome 1 read from result/PRSCSx/data/geno2/combinded.bim ...
... parse EUR sumstats file: result/PRSCSx/temple/Pancreatic_EUR.txt ...
... 12539161 SNPs read from result/PRSCSx/temple/Pancreatic_EUR.txt ...
... 91082 common SNPs in the EUR reference, EUR sumstats, and validation set ...
... parse EAS sumstats file: result/PRSCSx/temple/Pancreatic_EAS.txt ...
... 7300625 SNPs read from result/PRSCSx/temple/Pancreatic_EAS.txt ...
... 82024 common SNPs in the EAS reference, EAS sumstats, and validation set ...
... parse EUR reference LD on chromosome 1 ...
... parse EAS reference LD on chromosome 1 ...
... align reference LD on chromosome 1 across populations ...
... 94669 valid SNPs across populations ...
... MCMC ...
--- iter-100 ---
--- iter-200 ---
--- iter-300 ---
--- iter-400 ---
--- iter-500 ---
--- iter-600 ---
--- iter-700 ---
--- iter-800 ---
--- iter-900 ---
--- iter-1000 ---

Could you kindly advise if there are any strategies or optimizations available to address this challenge? I am keen to explore potential solutions to improve the computational performance and make better use of available resources.

Best regards,
Zilong

**Comment by getian107** [comment]
Hi Zilong - Could you provide more details on the computational efficiency? For example, how much time did it take to complete the computation for chromosome 1?

**Comment by caozilongsuper** [comment]
Hi Tian - About 38 hours and only used 5%~10% computational resource.

**Comment by getian107** [comment]
Yes there seems to be some issue. Usually the computation for one chromosome should be completed within 3 hours or so. Did you run the program on a local machine or on a compute cluster?

**Comment by caozilongsuper** [comment]
On a a compute cluster and many process are running on it at same time. But there still is idle computing resources ( %Cpu(s): 25.2 us).

**Comment by getian107** [comment]
Have you tried following the 'computational efficiency' section in the readme and adding the following lines to your script?

export MKL_NUM_THREADS=1
export NUMEXPR_NUM_THREADS=1
export OMP_NUM_THREADS=1

**Comment by caozilongsuper** [comment]
My problem has been solved!
Thank you for the quick reply
