### ISSUE TITLE
Referencing Error Occured 

### ISSUE THREAD

**Issue by joomango** [getian107/PRScsx#7]
Dear Dr. Tian,

I have encountered the following issue while running the PRS-csx:

**$ python3 /home/PRScsx/PRScsx.py ....

--ref_dir=/home/PRScsx/
--bim_prefix=/home/genotype
--sst_file=['/home/summarystats/GWAS_EA_forPRScs.txt']
--a=1
--b=0.5
--phi=0.01
--n_gwas=[766345]
--pop=['EUR']
--n_iter=1000
--n_burnin=500
--thin=5
--out_dir=/home/PRS/
--out_name=PRScs_test
--chrom=['22']
--meta=FALSE
--seed=777

##### process chromosome 22 #####
... parse bim file: /work2/07939/tg872382/stampede2/connectome/stampede2/WLS/Herd_WLS_TOP_subject_level.bim ...
... 10256 SNPs on chromosome 22 read from /work2/07939/tg872382/stampede2/connectome/stampede2/WLS/Herd_WLS_TOP_subject_level.bim ...
Traceback (most recent call last):
  File "/work2/07939/tg872382/stampede2/connectome/stampede2/PRScsx/PRScsx.py", line 204, in <module>
    main()
  File "/work2/07939/tg872382/stampede2/connectome/stampede2/PRScsx/PRScsx.py", line 187, in main
    sst_dict[pp] = parse_genet.parse_sumstats(ref_dict, vld_dict, param_dict['sst_file'][pp], param_dict['pop'][pp], param_dict['n_gwas'][pp])
UnboundLocalError: local variable 'ref_dict' referenced before assignment**

I very much appreciate that you had created the AMR ref panel. With your help, I would like to actively utilize PRS-csx for my current participants and your answer will be super helpful in using PRS-csx. Thank you so much, 

Yoonie

**Comment by getian107** [comment]
Hi Yoonie- did you pull the latest version of the software and download the updated SNP info file?

**Comment by joomango** [comment]
I pulled again and created another folder for LD reference data. It clarified the error. Thanks for your prompt and kind attention :)

**Comment by tillandlauer** [comment]
Dear Tian Ge,
I ran into the same error today:

```
Traceback (most recent call last):
  File "/git/PRScsx/PRScsx.py", line 215, in <module>
    main()
  File "/git/PRScsx/PRScsx.py", line 198, in main
    sst_dict[pp] = parse_genet.parse_sumstats(ref_dict, vld_dict, param_dict['sst_file'][pp], param_dict['pop'][pp], param_dict['n_gwas'][pp])
UnboundLocalError: local variable 'ref_dict' referenced before assignment
```

I have pulled the repository just before the run and downloaded the references / SNP info file.
It's the first time I tried to run PRScsx (PRScs works fine) so I don't know whether the error comes from my data or from the code.

Thanks for your support,
Till

**Comment by getian107** [comment]
@tillandlauer Hi Till- I got an email notification that you had an issue running PRS-CSx but somehow couldn't find your comment on GitHub. Is this resolved? If not it seems to be a problem when specifying the directory to the reference panels. It would be helpful if you send the command line that you used to call PRS-CSx.

**Comment by tillandlauer** [comment]
Good morning - thanks for replying!
I had the described issue but realised that I had, having copied the command from PRS-CS, accidentally left the path to the population-specific LD panel in the ref-dir path. So it was my fault of specifying the command wrongly and I didn't want to trouble you with it once I had found out. The error messages are a bit generic, i.e., when the SNP info file cannot be found no specific error message is produced. :)
By the way, do I understand correctly that there is no advantage in using PRS-CSx over PRS-CS if I have a GWAS meta-analysis combining studies from several ancestries without ancestry-specfic summary statistics available?

Best regards and thanks for your attentiveness,
Till


Am 3. April 2023 23:16:56 MESZ schrieb Tian Ge ***@***.***>:
>@tillandlauer Hi Till- I got an email notification that you had an issue running PRS-CSx but somehow couldn't find your comment on GitHub. Is this resolved? If not it seems to be a problem when specifying the directory to the reference panels. It would be helpful if you send the command line that you used to call PRS-CSx.
>

**Comment by JuRaGa** [comment]
Hello,

I get the same error, but didn't get from the previous comments how to solve it, please could you help me with that?

UnboundLocalError: local variable 'ref_dict' referenced before assignment

Thank you,
Julia

**Comment by getian107** [comment]
Hi Julia-- This error usually happens when the directory to the reference panel is not correctly specified. Please double check that --ref_dir points to a folder that contains the file "snpinfo_mult_1kg_hm3" and one or more of the population-specific references such as "ldblk_1kg_eur" and "ldblk_1kg_afr". If you can't find the problem, please send the command line that you used to call PRS-CSx, the full output log and a screenshot of the directory that --ref_dir points to if possible.

**Comment by JuRaGa** [comment]
Thank you Tian,

I was able to correct the error.

Best,
Julia
________________________________

**Comment by AnjeGrobler** [comment]
Hi there. 
I'm having trouble with PRScsx. When I run my code, it returns: "Traceback (most recent call last):
  File "/var/tmp/slurmd.spool/job1913445/slurm_script", line 28, in <module>
    import parse_genet
ModuleNotFoundError: No module named 'parse_genet'", however, I can very clearly see parse_genet in my directory. Please could you assist? It would be much appreciated!
Thank you, 
Anje

**Comment by getian107** [comment]
Hi Anje - Not sure what was the cause based on these information. Could you send (1) a snapshot of the directory where your saved the scripts, and (2) the command line that you used to call PRS-CSx?

**Comment by AnjeGrobler** [comment]
> Hi Anje - Not sure what was the cause based on these information. Could you send (1) a snapshot of the directory where your saved the scripts, and (2) the command line that you used to call PRS-CSx?

Hi Dr. Tian

Here are my screenshots attached. I am still quite young and learning how to use PRS-CSx as the first student at my university, so I would really appreciate your help. 

<img width="1405" alt="Screenshot 2024-01-09 at 21 25 41" src="https://github.com/getian107/PRScsx/assets/155960444/eefd892e-9eae-485f-a9f6-e47c4b18fb55">
<img width="1440" alt="Screenshot 2024-01-09 at 21 26 51" src="https://github.com/getian107/PRScsx/assets/155960444/0a458f8f-0233-411b-9744-0497cb547b73">

Thank you,
Anje

**Comment by getian107** [comment]
No worries Anje - Happy to help. I think the issue here is that you should refrain from modifying and running PRScsx.py directly. The usage section in the script merely provides an example of how to call the script. Instead, you should enter your command (python3 PRScsx.py --ref_dir...) into a terminal or include it in a different script from which you can call PRScsx.py.

**Comment by AnjeGrobler** [comment]
> No worries Anje - Happy to help. I think the issue here is that you should refrain from modifying and running PRScsx.py directly. The usage section in the script merely provides an example of how to call the script. Instead, you should enter your command (python3 PRScsx.py --ref_dir...) into a terminal or include it in a different script from which you can call PRScsx.py.

Oh, what a silly error! I appreciate your help. I  decided to run similar code in my terminal and received the following error: (which I don't understand as I am stipulating my sample size in the line of code)
<img width="1440" alt="Screenshot 2024-01-10 at 12 59 56" src="https://github.com/getian107/PRScsx/assets/155960444/c7250b10-7caf-41c0-8e5c-467c6284c9ed">

Would you kindly mind assisting me? 

Thank you in advance. Once again, your help is much appreciated.
Anje

**Comment by getian107** [comment]
In --sst_file, removing the space after comma might resolve the issue. You need to extract relevant columns from the FUMA files but all chromosomes can remain in a single file, and there is no requirement for them to be in a specific order.

**Comment by AnjeGrobler** [comment]
Thank you very much. That resolved my issue!

Best,
Anje

**Comment by jielab** [comment]
Hi, Prof. Ge:

Somehow I now encountered this same error mentioned by the above users. 

Please see my screenshot below. Can you please let me know what I might have done wrong.

![image](https://github.com/getian107/PRScsx/assets/26947455/ff6eff01-87e8-4836-9348-c95c0c3e03be)

BTW, for the option **--pop=AFR,EAS,EUR,SAS**, I can only specify a population name that exists in the LDREF folder (case insensitive), correct? That is, if I write  **--pop=BLACK,Asian,EUR,SAS**, PRS-CSx will complain, I guess.

Best regards,
Jie

**Comment by getian107** [comment]
- Please put 1KG and UKBB reference panels in separate folders.
- Please download SNP info files for 1KG and UKBB using the link on the read me page.
- Population input can only be one of the five: AFR, AMR, EAS, EUR, SAS.

**Comment by PheziweM** [comment]
Dear Dr. Tian,

I hope this message finds you well. I need your assistance regarding an issue I am encountering with my summary statistics data. I have encountered a problem with the summary statistics data, which was originally based on a different reference genome build than my target data. I used LiftOver to convert the summary statistics data from genome build 37 to build 38 to match the target dataset. Despite successfully performing the LiftOver, I am still facing an issue where the SNPs from the summary statistics are not being read by the tool (please see the attached image for reference).

I am unsure of what might be missing or going wrong with my summary statistics data.(attached) I would greatly appreciate any guidance or suggestions you might have to resolve this issue.
<img width="1440" alt="Screenshot 2024-06-04 at 00 07 09" src="https://github.com/getian107/PRScsx/assets/127058753/bd05c447-ca90-43ab-ad32-43de7e46dab3">
<img width="1440" alt="Screenshot 2024-06-04 at 00 07 03" src="https://github.com/getian107/PRScsx/assets/127058753/4adbe16e-ce0d-439b-b46f-78162b29dfbe">

**Comment by getian107** [comment]
Hi -- The format of the summary stats needs to be strictly followed, i.e., 5 columns with column names SNP, A1, A2, BETA (or OR), and SE (or P). Please see README for examples. Sorry for the limited flexibility.

**Comment by AHatziman** [comment]
Dear Dr. Tian,

Please find below a coding error I get when I call PRScs (v1.1.0) after updating 'scipy' on our systems, which terminates the analysis before the MCMC step. This occurs both on an institutional computer cluster (linux system) and my persona local macOS system both running python3 versions (3.11. and 3.13). 

It is strange though that when I tried in a different system running the old version of PRScs (v1.0) as well as python3/scipy modules (both downloaded much earlier -- end 2023) no similar error was occurred. To my view, the newest version of 'scipy' module causes the error.

The command "> python3 PRScs.py --help" runs just fine and no error is showing up.

Below I attach the error and the commands I've been using (with test files) for your convenience. Any help or recommendation to bypass this issue would be greatly appreciated.

Thank you in advance!

Best,
Alex
--------------------------------------------------------------------------------------------------------------------------
--ref_dir=/Users/alexandroshatzimanolis/Desktop/PRScs/PRScs-1.1.0/ldblk_1kg_eur
--bim_prefix=test
--sst_file=sumstats.txt
--a=1
--b=0.5
--phi=None
--n_gwas=50000
--n_iter=1000
--n_burnin=500
--thin=5
--out_dir=CHR22
--chrom=['22']
--beta_std=False
--write_psi=False
--seed=None


##### process chromosome 22 #####
... parse reference file: /Users/alexandroshatzimanolis/Desktop/PRScs/PRScs-1.1.0/ldblk_1kg_eur/snpinfo_1kg_hm3 ...
... 16464 SNPs on chromosome 22 read from /Users/alexandroshatzimanolis/Desktop/PRScs/PRScs-1.1.0/ldblk_1kg_eur/snpinfo_1kg_hm3 ...
... parse bim file: test.bim ...
... 1000 SNPs on chromosome 22 read from test.bim ...
... parse sumstats file: sumstats.txt ...
... 1000 SNPs read from sumstats.txt ...
... 1000 common SNPs in the reference, sumstats, and validation set ...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/scipy/__init__.py", line 137, in __getattr__
    return globals()[name]
           ~~~~~~~~~^^^^^^
KeyError: 'sqrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexandroshatzimanolis/Desktop/PRScs/PRScs-1.1.0/PRScs.py", line 115, in <module>
    main()
    ~~~~^^
  File "/Users/alexandroshatzimanolis/Desktop/PRScs/PRScs-1.1.0/PRScs.py", line 104, in main
    sst_dict = parse_genet.parse_sumstats(ref_dict, vld_dict, param_dict['sst_file'], param_dict['n_gwas'])
  File "/Users/alexandroshatzimanolis/Desktop/PRScs/PRScs-1.1.0/parse_genet.py", line 86, in parse_sumstats
    n_sqrt = sp.sqrt(n_subj)
             ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/scipy/__init__.py", line 139, in __getattr__
    raise AttributeError(
        f"Module 'scipy' has no attribute '{name}'"
    )
AttributeError: Module 'scipy' has no attribute 'sqrt'

**Comment by getian107** [comment]
Hi Alex -- If you pull the latest version from GitHub (not the official release), the issue should be resolved. We recently implemented a fix (see the version history section), but it hasn't been formally released or assigned a version number yet.

**Comment by AHatziman** [comment]
> Hi Alex -- If you pull the latest version from GitHub (not the official release), the issue should be resolved. We recently implemented a fix (see the version history section), but it hasn't been formally released or assigned a version number yet.

Thank you Tian for your quick reply, much appreciated!
