### ISSUE TITLE
Computing my own reference panel + other questions

### ISSUE THREAD

**Issue by privefl** [getian107/PRScsx#8]
In one of my papers, I have defined several ancestry groups in the UK Biobank:
![table1](https://user-images.githubusercontent.com/11161036/127128268-09cb7576-5a11-4b4c-a757-b1cd91cc6cd4.jpg)

I would like to run PRS-CSx on the training 2, i.e. using 7 different ancestry groups.

1. Is running PRS-CSx possible/suitable for this particular use case?

2. How could I compute my own reference panel for all these groups? Do you have a script to do this from e.g. bed files?

**Comment by getian107** [comment]
I think it's technically possible but so far our evaluation of the method has been focused on super-population levels. I'm not sure dividing continental populations into smaller subgroups would help or harm prediction, as many of the GWAS may be underpowered and the differences in effect size and LD patterns between some subpopulations may be limited. Building the reference panel for PRS-CSx is similar to building a panel for PRS-CS (https://github.com/getian107/PRScs/issues/20) although additional work is needed to link reference panels across populations. I don't have an automatic pipeline to do this yet but would be happy to share some scripts.

**Comment by privefl** [comment]
Should I group UK + Italy + Poland under EUR, remove Iran and use the LD ref panels from the UKBB that you provide then?

**Comment by getian107** [comment]
Yes- I think that might be a good starting point.
