### ISSUE TITLE
Results for all populations

### ISSUE THREAD

**Issue by privefl** [getian107/PRScsx#9]
I am trying PRS-CSx with 4 different populations.
It seems I get effects for the first one only.
Is it possible to get the PGS effects for all 4 populations in one go? Or am I doing something wrong?

**Comment by getian107** [comment]
It should be writing out posterior effects for all input populations in one go. If it doesn't work could you send the command line you used and the log output?

**Comment by privefl** [comment]
![cmd-prscsx](https://user-images.githubusercontent.com/11161036/127551038-ed5c27ca-0e2a-43ac-90e7-547b136238cb.jpg)
![log-prscsx](https://user-images.githubusercontent.com/11161036/127551034-9d8f058e-afac-4f69-a95f-db9e96f84d90.jpg)

I guess I'm doing something wrong.

**Comment by privefl** [comment]
I was doing something weird.

But you might want to avoid saying "align reference LD across populations" and replace it by something like "only one population provided" to make sure that users spot quickly that they might be doing something wrong (when they provide only one pop).

Thanks for the quick reply.

**Comment by getian107** [comment]
Thanks for the feedback- I've added a line in the log output to show the number of discovery populations.
